server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.10.1.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace